### ISSUE TITLE
Getting error while loading Data

### ISSUE THREAD

**Issue by MagicalForcee** [smthomas-sci/StyleALAE#1]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [4,4,4], [batch]: [4,4,3]
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]] [Op:IteratorGetNextAsOptional]

**Comment by smthomas-sci** [comment]
This code is not intended to run out of the box and requires an understanding of how the algorithm works. I encourage you to reverse engineer my code but I cannot provided support for its use nor do I provide any guarantee that it even works, let alone as it is described in the original paper.

**Comment by smthomas-sci** [comment]
This code is not intended to run out of the box and requires an understanding of how the algorithm works. I encourage you to reverse engineer my code but I cannot provided support for its use nor do I provide any guarantee that it even works, let alone as it is described in the original paper. This repo is a work in progress for research purposes to suit my own needs and is updated regularly. If you are wanting a stable implementation to play around with then it is probably best to look at the original PyTorch version.
